export const browserCoreExamples = [
  "opensoul browser status",
  "opensoul browser start",
  "opensoul browser stop",
  "opensoul browser tabs",
  "opensoul browser open https://example.com",
  "opensoul browser focus abcd1234",
  "opensoul browser close abcd1234",
  "opensoul browser screenshot",
  "opensoul browser screenshot --full-page",
  "opensoul browser screenshot --ref 12",
  "opensoul browser snapshot",
  "opensoul browser snapshot --format aria --limit 200",
  "opensoul browser snapshot --efficient",
  "opensoul browser snapshot --labels",
];

export const browserActionExamples = [
  "opensoul browser navigate https://example.com",
  "opensoul browser resize 1280 720",
  "opensoul browser click 12 --double",
  'opensoul browser type 23 "hello" --submit',
  "opensoul browser press Enter",
  "opensoul browser hover 44",
  "opensoul browser drag 10 11",
  "opensoul browser select 9 OptionA OptionB",
  "opensoul browser upload /tmp/file.pdf",
  'opensoul browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "opensoul browser dialog --accept",
  'opensoul browser wait --text "Done"',
  "opensoul browser evaluate --fn '(el) => el.textContent' --ref 7",
  "opensoul browser console --level error",
  "opensoul browser pdf",
];
